In [1]:
from simpsons_utils import *
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [2]:
raw_script_lines = pd.read_csv(SCRIPT_FILE)
filtered_script_lines = raw_script_lines[raw_script_lines["speaking_line"]==True]
filtered_script_lines = filtered_script_lines[KEY_EPISODE_INFORMATION]
sorted_script_lines = filtered_script_lines.sort_values(by=EPISODE_SORTING_KEY)
sorted_script_lines

C:\Users\rotax\AppData\Local\Temp\ipykernel_26420\686588658.py:1: DtypeWarning: Columns (4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_script_lines = pd.read_csv(SCRIPT_FILE)

,episode_id,timestamp_in_ms,character_id,spoken_words,word_count
0,32,848000,464.0,"No, actually, it was a little of both. Sometim...",31
1,32,856000,9.0,Where's Mr. Bergstrom?,3
2,32,856000,464.0,I don't know. Although I'd sure like to talk t...,22
3,32,864000,9.0,That life is worth living.,5
4,32,864000,40.0,The polls will be open from now until the end ...,33
...,...,...,...,...,...
131066,505,0,2.0,Then a kid disappears and it's total panic unt...,16
131068,505,0,2.0,...eating a thirty-dollar cheeseburger! Which ...,10
131070,505,0,2.0,And here's the worst part: I never get any tim...,22
131071,505,0,8.0,"Look, that's our ship!",4
130303,506,905000,2.0,What do I do?,4

In [3]:
raw_character_file = pd.read_csv(CHARACTER_FILE)
character_file = raw_character_file.drop(["name", "normalized_name"], axis=1)
labeled_script_lines = pd.merge(sorted_script_lines, character_file, left_on="character_id", right_on="id", how="left")
labeled_script_lines = labeled_script_lines.drop("id", axis=1)
labeled_script_lines = labeled_script_lines.dropna(axis=0)
labeled_script_lines.to_csv(SORTED_INFO, index=False)

In [4]:
labeled_script_lines

,episode_id,timestamp_in_ms,character_id,spoken_words,word_count,gender
0,32,848000,464.0,"No, actually, it was a little of both. Sometim...",31,f
1,32,856000,9.0,Where's Mr. Bergstrom?,3,f
2,32,856000,464.0,I don't know. Although I'd sure like to talk t...,22,f
3,32,864000,9.0,That life is worth living.,5,f
4,32,864000,40.0,The polls will be open from now until the end ...,33,f
...,...,...,...,...,...,...
109027,505,0,2.0,Then a kid disappears and it's total panic unt...,16,m
109028,505,0,2.0,...eating a thirty-dollar cheeseburger! Which ...,10,m
109029,505,0,2.0,And here's the worst part: I never get any tim...,22,m
109030,505,0,8.0,"Look, that's our ship!",4,m
109031,506,905000,2.0,What do I do?,4,m

In [5]:
nltk.download('stopwords')
nltk.download('punkt_tab')

stops = set(stopwords.words('english'))
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rotax\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\rotax\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [6]:
print(labeled_script_lines.shape)

(92703, 6)

In [7]:
# Remove stop words
stop_words_data = labeled_script_lines.copy()


i = 0
for line in stop_words_data["spoken_words"]:

    tokens = word_tokenize(line)
    filtered_list = [word.lower() for word in tokens if not word.lower() in stops and word.isalpha()]
    filtered_sentence = ' '.join(filtered_list)
    stop_words_data.iloc[i, 3] = filtered_sentence
    i += 1
    
    if i % 1000 == 0:
        print(f"Completed {i} / {stop_words_data.shape[0]}")
stop_words_data = stop_words_data.dropna(axis=0)

Completed 1000 / 92703
Completed 2000 / 92703
Completed 3000 / 92703
Completed 4000 / 92703
Completed 5000 / 92703
Completed 6000 / 92703
Completed 7000 / 92703
Completed 8000 / 92703
Completed 9000 / 92703
Completed 10000 / 92703
Completed 11000 / 92703
Completed 12000 / 92703
Completed 13000 / 92703
Completed 14000 / 92703
Completed 15000 / 92703
Completed 16000 / 92703
Completed 17000 / 92703
Completed 18000 / 92703
Completed 19000 / 92703
Completed 20000 / 92703
Completed 21000 / 92703
Completed 22000 / 92703
Completed 23000 / 92703
Completed 24000 / 92703
Completed 25000 / 92703
Completed 26000 / 92703
Completed 27000 / 92703
Completed 28000 / 92703
Completed 29000 / 92703
Completed 30000 / 92703
Completed 31000 / 92703
Completed 32000 / 92703
Completed 33000 / 92703
Completed 34000 / 92703
Completed 35000 / 92703
Completed 36000 / 92703
Completed 37000 / 92703
Completed 38000 / 92703
Completed 39000 / 92703
Completed 40000 / 92703
Completed 41000 / 92703
Completed 42000 / 92703
Completed 43000 / 92703
Completed 44000 / 92703
Completed 45000 / 92703
Completed 46000 / 92703
Completed 47000 / 92703
Completed 48000 / 92703
Completed 49000 / 92703
Completed 50000 / 92703
Completed 51000 / 92703
Completed 52000 / 92703
Completed 53000 / 92703
Completed 54000 / 92703
Completed 55000 / 92703
Completed 56000 / 92703
Completed 57000 / 92703
Completed 58000 / 92703
Completed 59000 / 92703
Completed 60000 / 92703
Completed 61000 / 92703
Completed 62000 / 92703
Completed 63000 / 92703
Completed 64000 / 92703
Completed 65000 / 92703
Completed 66000 / 92703
Completed 67000 / 92703
Completed 68000 / 92703
Completed 69000 / 92703
Completed 70000 / 92703
Completed 71000 / 92703
Completed 72000 / 92703
Completed 73000 / 92703
Completed 74000 / 92703
Completed 75000 / 92703
Completed 76000 / 92703
Completed 77000 / 92703
Completed 78000 / 92703
Completed 79000 / 92703
Completed 80000 / 92703
Completed 81000 / 92703
Completed 82000 / 92703
Completed 83000 / 92703
Completed 84000 / 92703
Completed 85000 / 92703
Completed 86000 / 92703
Completed 87000 / 92703
Completed 88000 / 92703
Completed 89000 / 92703
Completed 90000 / 92703
Completed 91000 / 92703
Completed 92000 / 92703

In [10]:
stop_words_data["spoken_words"].isna().value_counts()

spoken_words
False    92703
Name: count, dtype: int64

In [19]:
stop_words_data.to_csv(STOP_DATASET, index=False)
stop_words_data = pd.read_csv(STOP_DATASET)
stop_words_data = stop_words_data.dropna(axis=0)
stop_words_data.to_csv(STOP_DATASET, index=False)